
title: My Resume
#url: 'https://mlgruby.github.io'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Satyasheel
tagline: Data Engineer | MLOps | GCP 
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: satyasheel@ymail.com
# phone: (+91) 8130353677
website: satyasheel.me #do not add http://
github: mlgruby
twitter: '@s6012'
# stackoverflow: '1353861'
# blog: 
linkedin: ss6012



# Tracker
#analytics: UA-68140113-1
#Update all the sections by editing the files inside _includes folder.
